### PR TITLE
Create base template. Index extends base

### PR DESCRIPTION
**Pull request by ChrisFreeman**
-  Create base.html template with template blocks for top nav, left nav, body, footer, and postcontainer to allow adding pages with left nav, top nav, footer in common with index.html
  -- Create leftnav.html, topnav.html in new templates/nav directory
  -- Modify index.html to extend from new base.html.  Calendar moved to body block, calendar scripting moved to postcontainer block

### CODE REVIEW

**Comment by amory** [comment]
Awesome, thanks!

**Comment by ChrisFreeman** [comment]
Was it OK that I worked on the master branch.  I probably should have worked on a feature branch in my repo so that it would show up as a branch in the pull request.  Should using feature branches be the preferred flow?

**Comment by amory** [comment]
From my perspective, it's fine as long as you submit the pull request from
a forked repo. I can just fetch from your fork, review the request and then
merge. If I need to squash any commits I can do a merge --squash, although
I think that would make me the author of the commit and you wouldn't get
credit. Anyone else want to comment on pull request best practices?

**Comment by maxgarvey** [comment]
IMO, that sounds like pretty good flow:

create feature branch
work work work
pull request

get approval from review

maybe after approval, the implementor should hit merge button so as to get credit?
That or reviewer

**Comment by ChrisFreeman** [comment]
To get credit for the merge, doesn't one need to be a pdxpython repo owner to hit the button?

**Comment by amory** [comment]
To get credit for the merge, yes. You should get credit for the commit(s)
though. see
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile#how-are-commit-contributions-to-forks-counted

**Comment by ChrisFreeman** [comment]
At least one of these things must be true for us to count a commit contribution:
    - You have write access to the repository  `Nope`
    - You are a member of the organization that owns the repository  `Nope`
    - You have forked the repository   `Check`
    - You've opened an issue or PR on the repository   `Check`
    - You've starred the repository   `Check`

Looks like I'm golden with 3 qualifications.  :)

**Pull request merged**
